"""empty message

Revision ID: 2cef49143c32
Revises: 
Create Date: 2023-11-16 17:25:33.427782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cef49143c32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('request_uri', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('application', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit'))
    )
    op.create_table('country',
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('country_name', name=op.f('pk_country'))
    )
    op.create_table('parties',
    sa.Column('party_code', sa.String(), nullable=False),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('party_type', sa.String(), nullable=True),
    sa.Column('party_region', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('party_code', name=op.f('pk_parties'))
    )
    op.create_table('platforms',
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('card_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('platform_name', name=op.f('pk_platforms'))
    )
    op.create_table('user',
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), server_default='', nullable=False),
    sa.Column('last_name', sa.String(), server_default='', nullable=False),
    sa.Column('created_by', sa.String(), server_default='', nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), server_default='', nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Text(), server_default='user', nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('force_pwd_change', sa.Boolean(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email_id', name=op.f('pk_user')),
    sa.UniqueConstraint('email_id', name=op.f('uq_user_email_id'))
    )
    op.create_table('states',
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('long', sa.Integer(), nullable=True),
    sa.Column('rs_seats', sa.Integer(), nullable=True),
    sa.Column('ls_seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_name'], ['country.country_name'], name=op.f('fk_states_country_name_country')),
    sa.PrimaryKeyConstraint('state_code', name=op.f('pk_states'))
    )
    op.create_table('party_in_power',
    sa.Column('map_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('party_code', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_code'], ['parties.party_code'], name=op.f('fk_party_in_power_party_code_parties')),
    sa.ForeignKeyConstraint(['state_code'], ['states.state_code'], name=op.f('fk_party_in_power_state_code_states')),
    sa.PrimaryKeyConstraint('map_id', name=op.f('pk_party_in_power'))
    )
    op.create_table('platform_users',
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('profile_img', sa.String(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('behaviour_type', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['platform_name'], ['platforms.platform_name'], name=op.f('fk_platform_users_platform_name_platforms')),
    sa.ForeignKeyConstraint(['state_code'], ['states.state_code'], name=op.f('fk_platform_users_state_code_states')),
    sa.PrimaryKeyConstraint('email_id', name=op.f('pk_platform_users'))
    )
    op.create_table('politicians',
    sa.Column('politician_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('party_code', sa.String(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('politician_name', sa.String(), nullable=True),
    sa.Column('politician_img_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('activeness_group', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_code'], ['parties.party_code'], name=op.f('fk_politicians_party_code_parties')),
    sa.ForeignKeyConstraint(['state_code'], ['states.state_code'], name=op.f('fk_politicians_state_code_states')),
    sa.PrimaryKeyConstraint('politician_id', name=op.f('pk_politicians'))
    )
    op.create_table('pages',
    sa.Column('page_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['platform_name'], ['platforms.platform_name'], name=op.f('fk_pages_platform_name_platforms')),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.politician_id'], name=op.f('fk_pages_politician_id_politicians')),
    sa.PrimaryKeyConstraint('page_id', name=op.f('pk_pages'))
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('post_content', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], name=op.f('fk_posts_page_id_pages')),
    sa.PrimaryKeyConstraint('post_id', name=op.f('pk_posts'))
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('comment_content', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['platform_users.email_id'], name=op.f('fk_comments_email_id_platform_users')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name=op.f('fk_comments_post_id_posts')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('pk_comments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('pages')
    op.drop_table('politicians')
    op.drop_table('platform_users')
    op.drop_table('party_in_power')
    op.drop_table('states')
    op.drop_table('user')
    op.drop_table('platforms')
    op.drop_table('parties')
    op.drop_table('country')
    op.drop_table('audit')
    # ### end Alembic commands ###
